# Generated by Django 4.2.7 on 2025-10-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.AutoField(primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'department_list',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_list',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subId', models.AutoField(primary_key=True, serialize=False)),
                ('subName', models.CharField(max_length=100)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.department')),
            ],
            options={
                'db_table': 'subjects_list',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studId', models.AutoField(primary_key=True, serialize=False)),
                ('studKey', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.department')),
            ],
            options={
                'db_table': 'student_list',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classId', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=50)),
                ('year', models.CharField(choices=[('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=7)),
                ('semester', models.CharField(choices=[('Sem I', 'Semester I'), ('Sem II', 'Semester II'), ('Sem III', 'Semester III'), ('Sem IV', 'Semester IV'), ('Sem V', 'Semester V'), ('Sem VI', 'Semester VI')], max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.department')),
                ('students', models.ManyToManyField(to='attendance.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.teacher')),
            ],
            options={
                'db_table': 'classroom_list',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('sessionId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.classroom')),
            ],
            options={
                'db_table': 'attendance_session',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('recordId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(choices=[(True, 'Present'), (False, 'Absent')], default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
            options={
                'db_table': 'attendance_record',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
